name: test
on:
  push:
    branches:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install -y build-essential cmake b3sum librust-blake3-dev cmake pkg-config git
      - name: Install BLAKE3
        run: git clone https://github.com/BLAKE3-team/BLAKE3 && cd BLAKE3/c && cmake -S . -B build "-DCMAKE_INSTALL_PREFIX=/usr/local" && cmake --build build --target install
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B build
      - name: Build project
        run: cmake --build build --config Release
      - name: Run tests
        working-directory: ./build
        run: ctest -C Release